version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:5000/api
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
